"""fix original_filename name

Revision ID: 11671b998bb4
Revises: be904b1f35d1
Create Date: 2026-05-23 23:29:56.435946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11671b998bb4'
down_revision: Union[str, Sequence[str], None] = 'be904b1f35d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('original_filename', sa.String(), nullable=False))
    op.drop_column('file_uploads', 'original_filenme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('original_filenme', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('file_uploads', 'original_filename')
    # ### end Alembic commands ###
