"""add billing fields to User table

Revision ID: 14b1e3da14e9
Revises: 688e60cce88d
Create Date: 2026-05-18 01:16:14.876922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b1e3da14e9'
down_revision: Union[str, Sequence[str], None] = '688e60cce88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('stripe_subsctription_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    op.create_unique_constraint(None, 'users', ['stripe_subsctription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'plan')
    op.drop_column('users', 'stripe_subsctription_id')
    op.drop_column('users', 'stripe_customer_id')
    # ### end Alembic commands ###
