"""unify email tables

Revision ID: 688e60cce88d
Revises: 2ca058a6dd28
Create Date: 2026-05-17 17:45:06.332017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '688e60cce88d'
down_revision: Union[str, Sequence[str], None] = '2ca058a6dd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_emails_id'), table_name='scheduled_emails')
    op.drop_index(op.f('ix_scheduled_emails_to'), table_name='scheduled_emails')
    op.drop_table('scheduled_emails')
    op.add_column('emails', sa.Column('send_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('emails', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emails', sa.Column('error_message', sa.String(), nullable=True))
    op.alter_column('emails', 'to',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('emails', 'to',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('emails', 'error_message')
    op.drop_column('emails', 'sent_at')
    op.drop_column('emails', 'send_at')
    op.create_table('scheduled_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('send_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('scheduled_emails_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('scheduled_emails_pkey'))
    )
    op.create_index(op.f('ix_scheduled_emails_to'), 'scheduled_emails', ['to'], unique=False)
    op.create_index(op.f('ix_scheduled_emails_id'), 'scheduled_emails', ['id'], unique=False)
    # ### end Alembic commands ###
