"""fix Column name

Revision ID: 7449b4963c1d
Revises: 14b1e3da14e9
Create Date: 2026-05-18 15:55:25.580841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7449b4963c1d'
down_revision: Union[str, Sequence[str], None] = '14b1e3da14e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_stripe_subsctription_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['stripe_subscription_id'])
    op.drop_column('users', 'stripe_subsctription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_subsctription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_stripe_subsctription_id_key'), 'users', ['stripe_subsctription_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'stripe_subscription_id')
    # ### end Alembic commands ###
