"""fix email_verified column

Revision ID: 932932837422
Revises: 65343e71c462
Create Date: 2026-05-21 03:46:10.478620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '932932837422'
down_revision: Union[str, Sequence[str], None] = '65343e71c462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN email_verified TYPE BOOLEAN
        USING (
            CASE
                WHEN LOWER(email_verified) IN ('true', 't', '1', 'yes', 'y')
                THEN TRUE
                ELSE FALSE
            END
        )
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
