"""add user_id

Revision ID: cfcb12eda4de
Revises: fa6a285e497e
Create Date: 2026-03-18 07:29:47.430581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcb12eda4de'
down_revision: Union[str, Sequence[str], None] = 'fa6a285e497e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    op.add_column('scheduled_emails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scheduled_emails', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_emails', type_='foreignkey')
    op.drop_column('scheduled_emails', 'user_id')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'user_id')
    # ### end Alembic commands ###
