"""add refresh tokens table

Revision ID: febee8b6a717
Revises: cfcb12eda4de
Create Date: 2026-03-18 17:56:55.061412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febee8b6a717'
down_revision: Union[str, Sequence[str], None] = 'cfcb12eda4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emails', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('scheduled_emails', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_emails', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('emails', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
